### PR TITLE
Support new treesitter group names

### PR DESCRIPTION
**Pull request by luisiacc**
Hi there, I've translated the old treesitter group names to the new ones so this theme can support new treesitter versions.

This is what it looks like:

image

image

### CODE REVIEW

**Review by ful1e5 — APPROVED** [review]

**Review by ful1e5 — APPROVED** [review]

**Comment by ful1e5** [comment]
Thank you for your dedicated efforts and contributions!

**Comment by ful1e5** [comment]
I'm uncertain if this PR will resolve language-specific issues #220 and #215, but if it doesn't, I will fix them in the refactor. I am writing here to inform you all.

**Comment by karimdjemai** [comment]
#220 seems resolved now, thanks a lot!

**Comment by AlexXi19** [comment]
Hi, I still have the same issue as https://github.com/projekt0n/github-nvim-theme/issues/220 and also with a go project but I'm not seeing the changes reflected. I'm new to neovim and I'm using packer, how can I pull the latest changes from the PR? Thanks for your work on this project! 

Github Dark Default in VsCode 
image
Dark Default in nvim 
Screen Shot 2023-01-03 at 1 55 49 PM

**Comment by domvo** [comment]
Thanks for the fix and the project in general, it did change things for the better, but I still have a vastly different result compared to what's expected.

Left: nvim, right: vscode

Screenshot 2023-01-04 at 10 19 40

Maybe it's a misconfiguration on my side?

**Pull request merged**
