### PR TITLE
💄 Add iterm themes

### PR DESCRIPTION
**Pull request by metalelf0**
This adds three iterm themes, generated by converting the existing kitty ones manually to xresources format and converting them to iterm2 via terminal.sexy. The same thing can be easily done for other terminals, if needed.

### CODE REVIEW

**Review by ful1e5 — COMMENTED** [review]
Can we do with Lua templating. That reduces pain afterward when we change colors inside `colors.lua`.

Reference [extra lua module](https://github.com/projekt0n/github-nvim-theme/tree/main/lua/github-theme/extra)

**Comment by metalelf0** [comment]
I considered that, but I'm not that proficient with lua and preferred to provide a quick solution for people wanting iterm themes.

**Comment by metalelf0** [comment]
Ok, I've taken a dive into your code. The main problem is that while kitty and alacritty write colors as hex codes (`#aabbcc`) iterm2 wants them divided in three components (red, green and blue) where each component is represented as a float from 0 to 1. This is then written in an xml file, made of parts like this:

```
	<key>Ansi 10 Color</key>
	<dict>
		<key>Color Space</key>
		<string>sRGB</string>
		<key>Blue Component</key>
		<real>0.0784313725490196</real>
		<key>Green Component</key>
		<real>0.807843137254902</real>
		<key>Red Component</key>
		<real>0.0784313725490196</real>
	</dict>
```

Your code would need to be changed a lot to accomodate this: your `template` helper currently only does simple string interpolation. This means that we'd either need to prepare colors already divided in three components inside `colors.lua`, or change the template helper to accept functions (e.g. `<real>${iterm2_blue_component(black)}</real>`. The second solution is IMHO the best one, but I've tried and my lua isn't strong enough to get it working.

Do you have any hint about how to do this? Or any better solution?

Thanks and keep up the great work!

**Comment by ful1e5** [comment]
Try this util function for converting hex to RGB.

```lua
local hex2rgb = function(hex)
  local _, redColor, greenColor, blueColor = hex:match("(.)(..)(..)(..)")
  redColor, greenColor, blueColor =
      string.format("%0.16f", (tonumber(redColor, 16) / 255)),
      string.format("%0.16f", (tonumber(greenColor, 16) / 255)),
      string.format("%0.16f", (tonumber(blueColor, 16) / 255))
  return redColor, greenColor, blueColor
end
```

## Refrences 
- https://devforum.roblox.com/t/is-there-a-function-in-lua-similar-to-parsefloat/232465/9
- https://github.com/andrewyavors/Lua-Color-Converter/blob/a9f2ac9ebea95dc5e67643da30bfae36311d46a6/convertcolor.lua#L3-L11

**Comment by metalelf0** [comment]
Hey @ful1e5! I already managed to write a utility function to convert the individual colors. I still have to figure out a solution to properly pass them to the template, as adapting your `template` helper looks really difficult (instead of a single color, it would need three variables for each color). Maybe there's a simple way of doing that in lua I'm not aware of.

**Comment by ful1e5** [comment]
@metalelf0 Can you able share variable names according to `colors.lua`, Which you placed inside the key section (`Ansi 0,  Ansi 1, ..`).

**Comment by ful1e5** [comment]
I'm able to generate an itermcolors scheme with this bit of code. The only problem it has is colors.

### `lua/extra/init.lua`
```lua
package.path = "./lua/?/init.lua;./lua/?.lua"

local configModule = require("github-theme.config")

local function write(str, fileName)
  print("[write] extra/" .. fileName)
  local file = io.open("extras/" .. fileName, "w")
  file:write(str)
  file:close()
end

local extras = {kitty = "conf", alacritty = "yml", iterm = "itermcolors"}
for _, style in ipairs({"dark", "dimmed", "light"}) do
  configModule.themeStyle = style
  for extra, ext in pairs(extras) do
    local plugin = require("github-theme.extra." .. extra)
    write(plugin[extra](configModule), extra .. "_github_" .. style .. "." .. ext)
  end
end

```
### `lua/extra/iterm.lua`
```lua
local util = require("github-theme.util")
local configModule = require("github-theme.config")

local M = {}

local rgb = function(hex)
  local _, redColor, greenColor, blueColor = hex:match("(.)(..)(..)(..)")
  redColor, greenColor, blueColor =
      string.format("%0.16f", (tonumber(redColor, 16) / 255)),
      string.format("%0.16f", (tonumber(greenColor, 16) / 255)),
      string.format("%0.16f", (tonumber(blueColor, 16) / 255))
  return {r = redColor, g = greenColor, b = blueColor}
end

local keyToXML = function(key, color)
  local xml = util.template([[
	<key>${k} Text Color</key>
]], {k = key:gsub("__", " ")})

  xml = xml .. util.template([[
	<dict>
		<key>Color Space</key>
		<string>sRGB</string>
		<key>Blue Component</key>
		<real>${b}</real>
		<key>Green Component</key>
		<real>${g}</real>
		<key>Red Component</key>
		<real>${r}</real>
	</dict>
]], color)

  return xml
end

function M.iterm(config)
  config = config or configModule.config
  config.transform_colors = true
  local colors = require("github-theme.colors").setup(config)

  local itermColor = {
    Ansi__0 = rgb(colors.black),
    Ansi__1 = rgb(colors.red),
    Ansi__10 = rgb(colors.brightGreen),
    Ansi__11 = rgb(colors.brightYellow),
    Ansi__12 = rgb(colors.brightBlue),
    Ansi__13 = rgb(colors.brightMagenta),
    Ansi__14 = rgb(colors.brightCyan),
    Ansi__15 = rgb(colors.term_fg),
    Ansi__2 = rgb(colors.green),
    Ansi__3 = rgb(colors.yellow),
    Ansi__4 = rgb(colors.blue),
    Ansi__5 = rgb(colors.magenta),
    Ansi__6 = rgb(colors.cyan),
    Ansi__7 = rgb(colors.fg_dark),
    Ansi__8 = rgb(colors.fg_dark),
    Ansi__9 = rgb(colors.brightRed),
    Background = rgb(colors.bg),
    Bold = rgb(colors.fg),
    Cursor = rgb(colors.cursor),
    Cursor__Text = rgb(colors.bg),
    Forground = rgb(colors.fg),
    Selected__Text = rgb(colors.fg),
    Selection = rgb(colors.bg_visual_selection)
  }

  local iterm = [[
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
]]

  for k, c in pairs(itermColor) do iterm = iterm .. keyToXML(k, c) end

  iterm = iterm .. [[
</dict>
</plist>
]]

  return iterm
end

return M

```

**Comment by ful1e5** [comment]
try with new window of nvim with `nvim --cmd "set rtp+=$(pwd)" .` command.

**Comment by metalelf0** [comment]
Ok, running it with `make extra` works. I've fixed a couple typos and now it should be ready. I tested the color themes in iterm2 and they look ok to me.

**Review by ful1e5 — APPROVED** [review]
Amazing

**Pull request merged**
