### PR TITLE
feat: transparent background on lualine empty sections

### PR DESCRIPTION
**Pull request by bhushan**
This PR makes transparent background of the lualine empty sections.

Screenshot 2022-07-04 at 1 17 38 AM

For Light Mode and Other theme as well it makes transparent background.

Screenshot 2022-07-04 at 1 26 37 AM

### CODE REVIEW

**Review by ful1e5 — COMMENTED** [review]
Changing the lualine background color to a `bg` will cause inconsistency in the `transparent` mode.
Thanks for contributing.

**Comment by bhushan** [comment]
May i know ? which transparent mode ? And what in constancy? Is it possible to do it without this PR?

**Comment by bhushan** [comment]
Hi @ful1e5 .. could you please help me with transparency? How can i do it 🫠 ?

**Comment by bhushan** [comment]
@ful1e5 transparent mode looks horrible.. i wonder what is the use case of it 😅?

**Comment by bhushan** [comment]
Screenshot 2022-07-13 at 10 12 17 PM

Lualine still shows, black bg..

**Comment by bhushan** [comment]
Screenshot 2022-07-13 at 10 16 13 PM


I changed my terminal color to white then it looks good but i still have color on lualine..

**Comment by bhushan** [comment]
with my changes, and transparent mode, it works nicely.. 

Screenshot 2022-07-13 at 10 21 45 PM


Screenshot 2022-07-13 at 10 18 54 PM

**Review by ful1e5 — APPROVED** [review]

**Comment by smjonas** [comment]
Not sure if this was an improvement for all users :D When global statusline is enabled it now looks like this:

github_colorscheme_issue


Relevant settings:
```lua
o.laststatus = 3
o.fillchars:append {
  horiz = "━",
  horizup = "┻",
  horizdown = "┳",
  vert = "┃",
  vertleft = "┨",
  vertright = "┣",
  verthoriz = "╋",
}
```

**Comment by bhushan** [comment]
I think this is correct behaviour right ?

**Comment by smjonas** [comment]
Well there is no right or wrong, it's just preference. To me it looks worse than before because the separator is kind of "floating" now. Maybe there could be an option `transparent_statusline`?

**Comment by bhushan** [comment]
Let's see what @ful1e5 suggests.

**Pull request merged**
