### PR TITLE
fix: incorrect syntax highlighting

### PR DESCRIPTION
**Pull request by tmillr**
These changes might require multiple PR's in order to: quickly deliver highlight fixes, achieve cleaner/smaller pr's, etc.. Feedback and suggestions are welcomed!

It may be possible to refactor all of the `palette/*` files into a single file? Although I'm not sure if this is something that is wanted or desired, plus after all is said and done, there may remain some custom differences/tweaks among the different colorschemes when it comes to the non-syntax colors/highlights within these files? So for now, I am thinking that it may be best to simply put such questions (of refactoring, etc.) off until later, and in the meantime just develop a new file/module containing all of the common mappings (from hl-group to primer primitives color) that will then be `required()` within each of the `palette/*` files.

## Todo's, Notes, Ideas, Considerations, Etc.

- [x] Handle `rgb()` and `rgba()` color strings (not applicable to pl syntax colors)
- [ ] Interaction with user config and overrides
- [ ] Interaction with colorscheme compilation?
- [ ] Tests (at least manual testing/debugging for now, but ultimately proper tests ideally)
- [x] Go over `TODO` comments
- [x] Relocate + rename newly introduced types as needed
- [ ] Update CHANGELOG.md
- [x] Update other docs
- [x] Cleanup commits and commit messages
- [ ] Cleanup PR description

---

[wakatime](https://wakatime.com/@tmillr/projects/ebsxveoyhz?branches=fix-incorrect-highlights)

See #252

### CODE REVIEW

**Comment by tmillr** [comment]
Should be ready to merge soon! 👍

**Comment by tmillr** [comment]
@ful1e5 I think this one is pretty much ready (although it depends on #273 so that should be merged first). I think that further refinements such as tweaking highlights even further, refactoring, or addressing less commonly used languages, etc., can come later if needed. I didn't touch the CHANGELOG.

This pr ended up touching many files so it may be easier to view the diffs one commit at a time.

**Review by ful1e5 — APPROVED** [review]

**Review by ful1e5 — CHANGES_REQUESTED** [review]
Please make the necessary changes to [README.md#Configuration](https://github.com/projekt0n/github-nvim-theme#configuration).

**Comment by tmillr** [comment]
> Please make the necessary changes to [README.md#Configuration](https://github.com/projekt0n/github-nvim-theme#configuration).

Oops. Sorry for missing that.

See b4cbfe6437c5fa46006c0ccc75259582c5557a08

**Review by ful1e5 — APPROVED** [review]

**Review by ful1e5 — APPROVED** [review]

**Review by ful1e5 — APPROVED** [review]

**Review by ful1e5 — APPROVED** [review]

**Review by ful1e5 — APPROVED** [review]

**Pull request merged**
